# Query Google Cloud SQL (PostgreSQL), base source created by Gemini
#
# https://github.com/mattes/gce-cloudsql-proxy-action
# https://github.com/marketplace/actions/google-cloud-sql-proxy-action
#
# github actions - run sql script in postgres service
# https://stackoverflow.com/questions/63168549/github-actions-run-sql-script-in-postgres-service
#
# ERROR: (gcloud.sql.connect) It seems your client does not have ipv6 connectivity and the database instance does not have an ipv4 address.
# Please request an ipv4 address for this database instance.

name: Google Cloud SQL by Gemini

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  GCP_PROJECT_ID: "tpcg-datacollector"
  #PG_INSTANCE: "tpcg-datacollector:us-central1:posco-news-tmp"
  PG_INSTANCE: "posco-news-tmp"
  PG_HOST: "34.121.185.166"
  PG_PORT: "5432"
  PG_USER: "tpcg"
  PG_PWD: "root"
  PG_DB: "news-tmp"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://stackoverflow.com/questions/79173485/github-actions-cannot-upload-file-to-google-cloud-storage
      - name: Authenticate with GCP using Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.0.0
        with:
          project_id: tpcg-datacollector
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      # 2. PostgreSQL 클라이언트 설치
      - name: Connect to Cloud SQL and run query
        run:  |
          PGDATABASE=${{ env.PG_DB }} PGPASSWORD=${{ env.PG_PWD }} gcloud sql connect ${{ env.PG_INSTANCE }} --project=${{ env.GCP_PROJECT_ID }} --user=${{ env.PG_DB }} --quiet
          psql -c "SELECT * FROM tb_newscontent WHERE cast(writedate as date) = '2024-03-12' AND process_status=0 AND (title_eng is null or title_kor is null) LIMIT 5;" # 실행할 select 쿼리
