#
# https://github.com/mattes/gce-cloudsql-proxy-action
# https://github.com/marketplace/actions/google-cloud-sql-proxy-action
#
# github actions - run sql script in postgres service
# https://stackoverflow.com/questions/63168549/github-actions-run-sql-script-in-postgres-service

name: Database Process

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# cloud-sql-proxy tpcg-datacollector:us-central1:posco-news-tmp --credentials-file tpcg-datacollector.json
# psql "host=10.96.144.9 sslmode=disable dbname=news-tmp user=tpcg"
# psql "host=127.0.0.1 sslmode=disable dbname=news-tmp user=tpcg"
# psql "host=34.121.185.166 port=5432 sslmode=disable dbname=news-tmp user=tpcg"
env:
  PG_HOST: "34.121.185.166"
  PG_PORT: "5432"
  PG_USER: "tpcg"
  PG_PWD: "root"
  PG_DB: "news-tmp"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Connect DB
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: tpcg-datacollector:us-central1:posco-news-tmp
      - name: SELECT FROM
        uses: yakubique/query-postgresql@v1.2
        with:
          query: |
            SELECT * FROM tb_newscontent WHERE cast(writedate as date) = '2024-03-12' AND process_status=0 AND (title_eng is null or title_kor is null) LIMIT 5
          host: ${{ env.PG_HOST }}
          port: ${{ env.PG_PORT }}
          username: ${{ env.PG_USER }}
          password: ${{ env.PG_PWD }}
          db: ${{ env.PG_DB }}
          ssl: 'false'
