# This is a basic workflow to help you get started with Actions
# setup-gcloud GitHub Action
# https://github.com/google-github-actions/setup-gcloud

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: "tpcg-datacollector"
  BUCKET_NAME: "rubicon-data"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Getting latest Code
        uses: actions/checkout@v4

      # https://stackoverflow.com/questions/79173485/github-actions-cannot-upload-file-to-google-cloud-storage
      - name: Authenticate with GCP using Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
  
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2.0.0'
  
      - name: Use gcloud CLI
        run: 'gcloud info'
  
      #- name: Download JSON file from GCS
      #  uses: 'braineanear/gcp-storage-download@main'
      #  env:
      #    GCP_STORAGE_BUCKET: ${{ env.BUCKET_NAME }}
      #    SOURCE_DIR: "downloads/test.json"
      #    DEST_DIR: "github/test.json"

      # https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions
      #- name: Read JSON
      #  uses: actions/github-script@v6
      #  id: check-env
      #  with:
      #    result-encoding: string
      #    script: |
      #      try {
      #        const fs = require('fs')
      #        const jsonString = fs.readFileSync('./downloads/test.json')
      #        var apps = JSON.parse(jsonString)
      #      } catch(err) {
      #        core.error("Error while reading or parsing the JSON")
      #        core.setFailed(err)
      #      }

      #
      - name: Replace
        uses: rheuvel89/replace-action@v1
        with: 
          files: 'webhooks/test.txt'
          replacements: 'hello=hi,world=good'

      # Replace all the occurrences of 'hello' with 'world' in all the txt files,
      # excluding the node_modules folder
      - name: Replace multiple files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.txt'
          search-text: 'hello'
          replacement-text: 'world'
          exclude: 'node_modules/**'
          encoding: 'utf8'
          max-parallelism: 10

      # Replace all the occurrences of '{0}' with '42' in the README.md file
      - name: Replace a single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          search-text: '{0}'
          replacement-text: '42'

      - name: Push
        #uses: stefanzweifel/git-auto-commit-action@v4
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm --cached ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          git add .
          git commit -m "generated"
          git push --force
