# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: "tpcg-datacollector"
  BUCKET_NAME: "rubicon-data"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Getting latest Code
        uses: actions/checkout@v4

      # https://stackoverflow.com/questions/79173485/github-actions-cannot-upload-file-to-google-cloud-storage
      - name: Authenticate with GCP using Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
  
      - name: Setup GCP CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
  
      - name: Init Credentials
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud config set account sjkim@tpcg.co.kr
          gcloud auth login --cred-file=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Create GCS bucket if not exists
        run: |
          if ! gcloud storage ls gs://${{ env.BUCKET_NAME }}/; then
            gcloud storage buckets create --location=asia-northeast3 gs://${{ env.BUCKET_NAME }}/
          fi

      - name: Download a file from GCS
        run: |
          gcloud storage cp gs://${{ env.BUCKET_NAME }}/github/test.json ./downloads/

      # https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions
      - name: Read JSON
        uses: actions/github-script@v6
        id: check-env
        with:
          result-encoding: string
          script: |
            try {
              const fs = require('fs')
              const jsonString = fs.readFileSync('./downloads/test.json')
              var apps = JSON.parse(jsonString)
            } catch(err) {
              core.error("Error while reading or parsing the JSON")
              core.setFailed(err)
            }

      #
      - name: Replace
        uses: rheuvel89/replace-action@v1
        with: 
          files: 'webhooks/test.txt'
          replacements: 'hello=hi,world=good'

      # Replace all the occurrences of 'hello' with 'world' in all the txt files,
      # excluding the node_modules folder
      - name: Replace multiple files
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.txt'
          search-text: 'hello'
          replacement-text: 'world'
          exclude: 'node_modules/**'
          encoding: 'utf8'
          max-parallelism: 10

      # Replace all the occurrences of '{0}' with '42' in the README.md file
      - name: Replace a single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          search-text: '{0}'
          replacement-text: '42'

      - name: Sync
        uses: stefanzweifel/git-auto-commit-action@v4
